# SPDX-License-Identifier: Apache-2.0
# Copyright 2019 Intel Corporation
# Copyright 2020 Open Networking Foundation
# DPDK patched with AF_XDP CNI MULTIPORT SUPPORT
# NOTE/TODO UPDATE TESTPMD IMAGE TO LATEST PATCHSET - CURRENTLY THIS WILL NOT WORK WITH THE REFERENCED IMAGE
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: access-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: afxdp/access
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "afxdp",
    "mode": "primary",
    "logFile": "afxdp-cni.log",
    "logLevel": "debug",
    "ethtoolCmds" : ["-N -device- rx-flow-hash udp4 fn",
                     "-N -device- flow-type udp4 dst-port 2152 action 22",
                     "-N -device- flow-type udp4 dst-port 8805 action 1"
                    ],
    "ipam": {
        "type": "host-local",
        "subnet": "198.18.0.0/30",
        "rangeStart": "198.18.0.1",
        "rangeEnd": "198.18.0.1",
        "gateway": "198.18.0.2"
    }
}'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: core-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: afxdp/core
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "afxdp",
    "mode": "primary",
    "logFile": "afxdp-cni.log",
    "logLevel": "debug",
    "ethtoolCmds" : ["-N -device- rx-flow-hash udp4 fn",
                     "-N -device- flow-type udp4 dst-port 2152 action 22",
                     "-N -device- flow-type udp4 dst-port 8805 action 1"
                    ],
    "ipam": {
        "type": "host-local",
        "subnet": "198.19.0.0/30",
        "rangeStart": "198.19.0.1",
        "rangeEnd": "198.19.0.1",
        "gateway": "198.19.0.2"
    }
}'
---
apiVersion: v1
kind: Pod
metadata:
  name: dpdk
  labels:
    app: dpdk
  annotations:
      k8s.v1.cni.cncf.io/networks: access-net, core-net
spec:
  shareProcessNamespace: true
  initContainers:
  # Currently CNI doesn't allow metric we're doing it here instead of net-attach-def
  - name: routes
    image: quay.io/mtahhan/dpdk:latest
    env:
    - name: ENB_SUBNET
      value: '11.1.1.128/25'
    - name: S1U_GATEWAY
      value: '198.18.0.2'
    - name: SGI_GATEWAY
      value: '198.19.0.2'
    command: ["sh", "-xec"]
    args:
    - ip route add 11.1.1.128/25 via 198.18.0.2 dev ens3f0np0 metric 100;
      ip route add default via 198.19.0.2 dev ens3f1np1 metric 100;
      ip neighbor add 198.18.0.2 lladdr 40:a6:b7:96:bc:50 dev ens3f0np0;
      ip neighbor add 198.19.0.2 lladdr 40:a6:b7:96:bc:51 dev ens3f1np1;
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
  containers:
  - name: testpmd
    image: quay.io/mtahhan/dpdk:latest
    command: ["tail", "-f", "/dev/null"]
    #command: ["sh", "-c", "./build/app/dpdk-testpmd --log-level pmd.net.af_xdp:debug  -l 0-2 --no-pci --main-lcore=2 --vdev net_af_xdp0,iface=ens3f0np0,start_queue=22,queue_count=1,use_cni=1,sock=/tmp/afxdp_dp/ens3f0np0/afxdp.sock --vdev net_af_xdp1,iface=ens3f1np1,start_queue=22,queue_count=1,use_cni=1,sock=/tmp/afxdp_dp/ens3f1np1/afxdp.sock -- -i --a --nb-cores=2 --rxq=1 --txq=1 --forward-mode=macswap;"]
    securityContext:
      capabilities:
        add:
          - NET_RAW
          - IPC_LOCK
    resources:
      limits:
        hugepages-1Gi: 2Gi
        cpu: 2
        memory: 256Mi
        afxdp/access: '1'
        afxdp/core: '1'
    volumeMounts:
    - name: hugepages
      mountPath: /dev/hugepages
  volumes:
  - name: hugepages
    emptyDir:
      medium: HugePages
